### ISSUE TITLE
can't locate stryker report

### ISSUE THREAD

**Issue by RLWells-1984** [tpugh/mutation-lab-class-2#4]
The screen shot in the project instructions does not match what I see for step 9. When clicking actions I get:
![image](https://user-images.githubusercontent.com/68760613/167025299-dc12f9b2-1027-4812-9865-535544301379.png)

There is no summary button and no artifacts. I'm lost, any help locating the correct spot would be great. Thank you.

**Comment by tpugh** [comment]
@RLWells-1984  thank you for reaching out I just merged in your pull request and you will be able to find your report at the bottom of this [page ](https://github.com/tpugh/mutation-lab-class-2/actions/runs/2278272585) when the CI/CD pipeline finishes.  it will say stryker-report under Artifacts.

**Comment by tpugh** [comment]
In the image you posted above, if you click your group on the left side you will see the latest CI job at the top of the list. If you click that you  should end up at this link where a link for your Stryker report will be located at the bottom of the page. 

https://github.com/tpugh/mutation-lab-class-2/actions/runs/2278272585

**Comment by tpugh** [comment]
@RLWells-1984 just verified that your job finished and Stryker report is at the link above, thanks for bringing up issue.

**Comment by dsagala** [comment]
I cannot find the Stryker report either. Could you please merge my pull request. Thanks.

**Comment by tpugh** [comment]
@dsagala your stryker report for group seven can be found here: https://github.com/tpugh/mutation-lab-class-2/actions/runs/2328704085

**Comment by tpugh** [comment]
# Finding Stryker Report 

Step 1 on the repo's home page click the actions tab

![step_1](https://user-images.githubusercontent.com/5107864/168505986-633f3435-31fb-44fc-8d64-1a6e1a4ec266.png)


step 2 click your group, see 1 as an example on the image below, then click the top green job (2nd circle in image below)

![step_2](https://user-images.githubusercontent.com/5107864/168506023-cfcb465e-f65e-4e4a-965e-b32669c3e543.png)


step 3 after completing the two clicks in image above you will see the view below, there will be a box icon with the words stryker-report on the bottom of the page, depending on the file and its size, there might be more artifacts listed than what you see below, but the stryker report will be below the artifacts. after you click stryker report, you will have a json file that you can upload to the reports director.

![step_3](https://user-images.githubusercontent.com/5107864/168506041-cacdbec3-7feb-4a1d-8df8-2c61da33c1f1.png)

**Comment by barshakafle** [comment]
Hi I am group 3 and i found the Stryker Report and I was trying to open it to view the code/mutant but I am unable to do so. Whenever I try to open the group.html file I am shown this error message. 
"TypeError: Failed to fetch"

**Comment by tpugh** [comment]
@barshakafle if you try to view that file locally you would need to run an http server. There is a site deployed with all of the results [here](https://tpugh.github.io/mutation-viewer/#mutant) so you don't have to worry about viewing locally.
